spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.20.0.3:5432/test_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      org:
        hibernate:
          jdbc:
            time_zone: UTC
