spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.20.0.2:5432/test_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      org:
        hibernate:
          jdbc:
            time_zone: UTC
  application:
    name: comment-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
