spring:
  application:
    name: dispatch-service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.value}
queues:
  tweet:
    creation: tweets.create
exchanges:
  twitter: twitter-exchange    